### ISSUE TITLE
0.3.2 Unable to start local service

### ISSUE THREAD

**Issue by zc317414** [lmstudio-ai/lmstudio-bug-tracker#106]
[ERROR] Error starting server {"code":"EACCES","errno":-4092,"syscall":"listen","address":"127.0.0.1","port":1234}

**Comment by mortel1o** [comment]
hi
how did you solve the problem?
i faced the same

**Comment by windssykwt** [comment]
> hi how did you solve the problem? i faced the same
@mortel1o 
you should change the port or kill some service that using default port LM Studio at server port: 1234
