### ISSUE TITLE
How do I save my config? 

### ISSUE THREAD

**Issue by peter-ch** [lmstudio-ai/lmstudio-bug-tracker#122]
Every time I load a model the config resets. Why do I have to set the value 8192 every goddamn time I load a model? But it's worse, my custom system prompt disappears with every new chat. So I have to enter it over and over again every time I create a new chat. Am I not seeing how to make it persistent?

**Comment by yagil** [comment]
Which LM Studio version?  Are you on 0.3.2?

**Comment by peter-ch** [comment]
Yes, 0.3.2.

**Comment by yagil** [comment]
0.2.* style Presets are on the way, which will likely solve this easily.

In the meantime:

- System prompts are indeed per-chat. The best solution for now is copy-paste, or duplicate the chat
- You can utilize the "Remember settings for..." checkbox to keep 8192 for the particular model

![image](https://github.com/user-attachments/assets/92f557f4-7c1a-487e-8dee-30f6cb557b3b)

**Comment by peter-ch** [comment]
Ok, thanks!
