### ISSUE TITLE
0.3.3 LM Studio cannot load models, Error: 'Cannot read properties of undefined'

### ISSUE THREAD

**Issue by labsnoir** [lmstudio-ai/lmstudio-bug-tracker#138]
Since the update to 0.3.3, models cannot be loaded anymore.
When trying to load any model, the following message appears:
`Attempt to pull a snapshot of system resources failed. Error: 'Cannot read properties of undefined (reading 'pullReport')'`

![{9F68F59C-B8AE-4AB6-9FCF-54379E7221A4}](https://github.com/user-attachments/assets/3ab5eb76-6030-4543-8191-eb8d0dd2b41c)

I don't know if this is relevant, but the system resources tab looks like this:
![grafik](https://github.com/user-attachments/assets/ff426ced-84b1-444f-8d1d-6bfd0f252f2a)

The device is:
Windows 11 Home 24H2
Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Oryon(TM) CPU   3.42 GHz
32 GB Ram

Any help is appreciated.

**Comment by yagil** [comment]
Hello @labsnoir this might not be the Snapdragon specific version.
Can you please try to redownload from the website?   Specifically: https://lmstudio.ai/download?os=win&arch=arm64

**Comment by labsnoir** [comment]
Yes, this works, thank you!
