### ISSUE TITLE
Document attachments do not appear to work

### ISSUE THREAD

**Issue by brool** [lmstudio-ai/lmstudio-bug-tracker#144]
Version: 0.3.4
Apple Silicon

Attached a text document, ran a query. Assistant said:

```
Chosen context injection strategy: 'retrieval'. Retrieval is optimal for the size of content provided
Retrieving relevant citations for user query...
```

and then errored out:

```
Failed to send message
Fork path does not exist.
ENOENT: no such file or directory, access '/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/retrievalworker.js'
```

**EDIT**: "embed" works for me, it's "retrieval" that seems to be referring to a missing file.

**Comment by hokie911** [comment]
Thank you for reporting this. I experiences the same error when I attempted to upload a PDF file attachment. 

I would like to obtain the 0.3.2 version, which is the most stable one for me so far.

**Comment by yagil** [comment]
We've found the issue and we're fixing it. We'll publish the fix as 0.3.4 build 2. I'll share it here when it's ready

**Comment by brool** [comment]
With build 2, I'm getting: 

```
dlopen(./.webpack/main/libsqlite-vector.dylib.dylib, 0x000A): tried: './.webpack/main/libsqlite-vector.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS./.webpack/main/libsqlite-vector.dylib.dylib' (no such file), '/Applications/LM Studio.app/Contents/Frameworks/./.webpack/main/libsqlite-vector.dylib.dylib'
```

**Comment by yagil** [comment]
@brool thanks, sorry about that. Fixing and will update here

**Comment by yagil** [comment]
@brool should be fixed now with build **3**.  https://lmstudio.ai/download. 
Please let me know if you're still running into issues.

**Comment by brool** [comment]
Works with my test cases, tried both retrieval and "inject-full-content", all looks good! Very awesome.

**Comment by hokie911** [comment]
Works for me as well. Thank you @yagil!
