### ISSUE TITLE
Failed to send message - Error in iterating prediction stream: TypeError: bfloat16 arrays cannot be converted directly to NumPy.

### ISSUE THREAD

**Issue by HenkPoley** [lmstudio-ai/lmstudio-bug-tracker#147]
When using mlx-community/Llama-3.2-1B-Instruct-bf16 LM Studio 0.3.4 gives me this error at the end 🤔 (MacBook M1).

Failed to send message
Error in iterating prediction stream: TypeError: bfloat16 arrays cannot be converted directly to NumPy.

It otherwise just works.

**Comment by cristian-rivera** [comment]
+

**Comment by yagil** [comment]
This should be fixed with 0.3.4 build 5, available here https://lmstudio.ai/download

**Comment by HenkPoley** [comment]
No more error in LM Studio 0.3.4 build 5.
