### ISSUE TITLE
Per-model Defaults icon missing

### ISSUE THREAD

**Issue by GitGrove** [lmstudio-ai/lmstudio-bug-tracker#224]
I'm trying to set per-model defaults per this help article https://lmstudio.ai/docs/configuration/per-model

The gear icon to edit those settings does not exist in the current version of LM Studio for Windows.

![Capture](https://github.com/user-attachments/assets/0c5195ed-5947-4308-92a2-d94e1f1499bb)

**Comment by yagil** [comment]
Hi @GitGrove indeed this is new in 0.3.*.  You can get it from https://lmstudio.ai

**Comment by GitGrove** [comment]
Hey, thanks for the quick reply @yagil! I'm on 0.2.31 and the app says it's up to date. Is _that_ a bug or is the repo that the updater relies on not up to date?

**Comment by GitGrove** [comment]
Never, mind. I see there's not in-place upgrade for 0.2 to 0.3 without reinstalling. Thanks!
