### ISSUE TITLE
Changing the binary behind download link breaks Distribution (in Nixpkgs)

### ISSUE THREAD

**Issue by eeedean** [lmstudio-ai/lmstudio-bug-tracker#25]
Hello LMStudio-Team,

much appreciate your efforts, building a great tool for working with LLMs locally. I'm a fan and love to use it almost every productive day.  

I'm writing you as a maintainer of the lmstudio package in [nixpkgs](https://github.com/NixOS/nixpkgs), [one of the largest and most up to date repositories](https://repology.org/repositories/graphs). We recently had an issue, because you have changed the binary available under the download link (https://releases.lmstudio.ai/mac/arm64/0.2.22/b/latest/LM-Studio-0.2.22-arm64.dmg at the time), which results in [breaking the lmstudio package for Nix(OS)](https://github.com/NixOS/nixpkgs/pull/310914#issuecomment-2106221288). 

A stable download link is favourable, because it gives us the security, that the package we download is exactly the package, we expect it to be. This does help avoiding supply chain attacks, as well as just gives general reliability, as it does keep every operation reproducible. 
If there was a critical (especially security) issue, I think, everyone can understand quite well, that you would want to stop distribution altogether ASAP, however that's not the case, as far as I'm informed. 

I fear, with breaking existing binary download links, we might lose acceptance for the package in Nixpkgs altogether. 
I would be glad to keep the package available to NixOS users using the official Nixpkgs repository. 

Is it possible to establish some pattern of stable download links, serving the same binary for as long of a period as possible? 

Thanks a lot for your time. 

Best Regards
Dean

**Comment by yagil** [comment]
@eeedean thank you very much for your message here. You are heard! Didn't mean to cause headaches on your side. We will not override the binaries moving forward. We're moving to a `version/letter` scheme where the letter indicates the revision build of a given version. If something like this happens in the future we're available here and on team@lmstudio.ai and would be happy to sort it out with you. Hopefully that won't be necessary though. Sorry again.

**Comment by eeedean** [comment]
@yagil  thanks a lot for your very prompt response. We're glad to be heard and are looking forward into a reproducible future. 😸 

That issue is resolved then, I think. 

Thanks again!
