### ISSUE TITLE
I am using M4 Max 128GB RAM  use MLX is much slower than GGUF

### ISSUE THREAD

**Issue by guanyingkai1984** [lmstudio-ai/lmstudio-bug-tracker#258]
I am using M4 Max, using LM studio to use MLX is much slower than GGUF. I think it may be due to there is more setting for GGUF, and i can change the GPU offload, and CPU Threads

**Comment by yagil** [comment]
Hi @guanyingkai1984 can you please share the following?

1. the hugging face link to the GGUF model
2. the hugging face link to the MLX model
3. screenshots showing the MLX speed vs GGUF speed

Thanks!

**Comment by yagil** [comment]
Thanks for sharing more details @guanyingkai1984, however you're comparing **duration** which is not sufficient to determine what's faster.  If you want, please share information showing **token / sec**. You get this in the LM Studio UI or by using our (not yet stable) [REST API](https://lmstudio.ai/docs/api/rest-api).  I'm closing this for now because unless it's an edge case we're not aware of, this is likely just a measurement mistake.

**Comment by guanyingkai1984** [comment]
Thanks for your reply. 
I do not think it is measurement mistake, the time i show you measure the time to run for the first 25 rows in CSV only.
And i need to run more than 20K of rows in a CSV file. The time different is huge,

The PY code is run in your local API. 
So, but i cannot see where you show token per second.
It would be great if you can show me how to record the token per second.
Developer log only show how many second between completion of each run.

**Comment by guanyingkai1984** [comment]
GGUF log:

2024-12-19 16:08:12  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:08:12  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:08:12  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:08:46  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:08:47  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:08:47  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:08:47  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:08:55  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:08:55  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:08:55  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:08:55  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:09:03  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:09:04  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:09:04  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:09:04  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:09:12  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:09:12  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:09:12  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:09:12  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:09:20  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:09:21  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:09:21  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:09:21  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:09:28  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:09:29  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:09:29  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:09:29  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:09:35  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:09:36  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:09:36  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:09:36  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:09:45  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:09:46  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:09:46  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:09:46  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:09:53  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:09:54  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:09:54  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:09:54  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:10:02  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:10:02  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:10:02  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:10:02  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:10:10  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:10:10  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:10:10  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:10:10  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:10:18  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:10:19  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:10:19  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:10:19  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:10:26  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:10:26  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:10:26  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:10:26  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:10:34  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:10:35  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:10:35  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:10:35  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:10:43  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:10:44  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:10:44  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:10:44  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:10:51  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:10:52  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:10:52  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:10:52  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:10:59  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:11:00  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:11:00  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:11:00  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:11:07  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:11:07  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:11:07  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:11:07  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:11:14  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:11:15  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:11:15  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:11:15  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:11:22  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:11:23  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:11:23  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:11:23  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:11:30  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:11:30  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:11:30  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:11:30  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:11:37  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:11:38  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:11:38  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:11:38  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:11:45  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:11:45  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:11:45  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:11:45  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:11:53  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:11:53  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:11:53  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-12-19 16:11:53  [INFO] 
[LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-12-19 16:12:01  [INFO] 
[LM STUDIO SERVER] Accumulating tokens ... (stream = false)
2024-12-19 16:12:02  [INFO] 
[LM STUDIO SERVER] [lmstudio-community/llama-3.3-70b-instruct] Generated prediction: [Hidden]
2024-12-19 16:12:02  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..

**Comment by Caojunisstudying** [comment]
> Hi [@guanyingkai1984](https://github.com/guanyingkai1984) can you please share the following?
> 
> 1. the hugging face link to the GGUF model
> 2. the hugging face link to the MLX model
> 3. screenshots showing the MLX speed vs GGUF speed
> 
> Thanks!

when I use the MLX model,my Macmini takes up much more memory than the GGUF version on OLLAMA，why？if OLLAMA use the full size of ram running the GGUF model but LM studio just use the vram running the mlx model？

**Comment by guanyingkai1984** [comment]
Hello [Caojunisstudying]
Thank for the Email.
Things become even more funny now. 
I think started from two weeks ago,
The RTX 4070 laptop with 8G VRAM + 64GB RAM is **much faster** than the Mac 4 MAX 40-core GPU 128G URAM
running Llama-3.3-70B (Q4)
============4070 LAPTOP===========

lmstudio-community/Llama-3.3-70B-Instruct-GGUF/Llama-3.3-70B-Instruct-Q4_K_M.gguf

On average less than 30s per run
=============M4 MAX =============

mlx-community/Llama-3.3-70B-Instruct-4bit

On average over than 40s per run
