### ISSUE TITLE
Chats with assistant tool-call messages having `"content": null` are erroneously rejected

### ISSUE THREAD

**Issue by alexchandel** [lmstudio-ai/lmstudio-bug-tracker#261]
When LM Studio returns a tool call to a client, and the chat is continued with the assistant's tool-call message having `"content": null`, it is erroneously rejected:

```
2024-12-18 21:49:18 [DEBUG] 
Received request: POST to /v1/chat/completions with body {
  "messages": [
    {
      "role": "user",
      "content": "Get the secret number, using any tool you have access to."
    },
    {
      "role": "assistant",
      "content": null,
      "tool_calls": [
        {
          "id": "6b17b9368",
          "type": "function",
          "function": {
            "name": "get_secret_number",
            "arguments": "{}"
          }
        }
      ]
    },
    {
      "role": "tool",
      "tool_call_id": "6b17b9368",
      "content": "42.69"
    }
  ],
  "model": "qwen2.5-7b-instruct",
  "parallel_tool_calls": false,
  "stream": true,
  "stream_options": {
    "include_usage": true
  },
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_secret_number",
        "parameters": {
          "properties": {},
          "type": "object"
        },
        "description": "Get the secret number."
      }
    }
  ]
}
2024-12-18 21:49:18 [ERROR] 
[Server Error] Invalid 'content': 'content' field must be a string or an array of objects.
```

This conflicts with OpenAI's examples for the schema, where `"content": null` is explicitly present and accepted: https://platform.openai.com/docs/api-reference/chat/create

<img alt="image" width="400" src="https://private-user-images.githubusercontent.com/6640905/397414314-3eef135c-0506-46fa-8b49-64b333858853.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NjM0NTQsIm5iZiI6MTczNDY2MzE1NCwicGF0aCI6Ii82NjQwOTA1LzM5NzQxNDMxNC0zZWVmMTM1Yy0wNTA2LTQ2ZmEtOGI0OS02NGIzMzM4NTg4NTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjBUMDI1MjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBhMTZjNDcyNmJiMzhkYTk4ZDI0Nzk0YjNhNWM3NDMxZGI1OTg0Yjk2YmUxZTIwZGM1NzEwMDBjOWRkOWIxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.V_MbEpYR0XhTDXfCv0yMhWPw22cmDz-N0Wf0cpOkJ2M"> <img alt="image" width="400" src="https://private-user-images.githubusercontent.com/6640905/397414495-8a3df392-a99b-4028-b707-493f555c3fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NjM0NTQsIm5iZiI6MTczNDY2MzE1NCwicGF0aCI6Ii82NjQwOTA1LzM5NzQxNDQ5NS04YTNkZjM5Mi1hOTliLTQwMjgtYjcwNy00OTNmNTU1YzNmYTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjBUMDI1MjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDcyODc5NzAxOTgxZDZmM2EwZjAwYzA0NGE3ZGE3MzViYzdmMWE1YTRkYjgzMDkwYTEwNjNjZmU4N2NiMGFiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.n8d_ZAif7_LkM6pocjGN7QCDTVgrYl0Lxp2g6Eexutc">

**Comment by yagil** [comment]
Thanks @alexchandel. To confirm, this is with build 9?

**Comment by alexchandel** [comment]
yes, build 9

**Comment by mattjcly** [comment]
Fixed for next beta/stable release 👍
