### ISSUE TITLE
Cannot read properties of undefined (reading 'messages')

### ISSUE THREAD

**Issue by Tzebruh** [lmstudio-ai/lmstudio-bug-tracker#29]
Can't open the chat page. The error says _Cannot read properties of undefined (reading 'messages')_

**Comment by yagil** [comment]
@JustinBustin5 thanks, a few questions:

1. which operating system?
2. Which version of the app?
3. Is this the first time you use the app, or is this a new issue after an update?

**Comment by yagil** [comment]
Thanks, no worries. 

We released 0.2.24 yesterday, do you mind giving it a try? https://lmstudio.ai

**Comment by yagil** [comment]
It's possible. The chats are stored in `~/.cache/lm-studio/chats`. As a quick experiment you could rename your chats directory to `chats_backup`, create a new `chats` folder and restart the app
