### ISSUE TITLE
Failed to Start LM Studio

### ISSUE THREAD

**Issue by PizzaThatCodes** [lmstudio-ai/lmstudio-bug-tracker#34]
When running the installer for windows I get:
![image](https://github.com/lmstudio-ai/lmstudio-bug-tracker/assets/61859244/a97163c4-54f4-432b-99ec-eb995fc0e95b)

**Comment by PizzaThatCodes** [comment]
Running windows 10 btw

**Comment by YorkieDev** [comment]
Hi, this error message occurs when a CPU doesn't support AVX2 instructions. What CPU do you have in your machine?

**Comment by PizzaThatCodes** [comment]
Intel i7-3770K

**Comment by PizzaThatCodes** [comment]
3770k doesn’t have AVX2 instructions which is currently a hard requirement for LM Studio. There’s an old deprecated 0.2.10 beta with AVX support.
