### ISSUE TITLE
GPU Offload is inactive in version 0.2.25, but I can select it in 0.2.24

### ISSUE THREAD

**Issue by rsvr88** [lmstudio-ai/lmstudio-bug-tracker#40]
GPU Offload is inactive in version 0.2.25, but I can select it in 0.2.24
vicuna-13b-v1.5.Q5_K_M
AMD RX 6600 XT

**Comment by YorkieDev** [comment]
Hi @rsvr88 due to OpenCL being deprecated in the version of llama.cpp uses in LM Studio, you have to manually add OpenCL support by following the instructions here:

https://github.com/lmstudio-ai/configs/blob/main/Extension-Pack-Instructions.md

**Comment by rsvr88** [comment]
Hi @YorkieDev Now I can select GPU Offload, thank you!
