### ISSUE TITLE
Gemma 2 significantly worse in 0.2.27 

### ISSUE THREAD

**Issue by peter-ch** [lmstudio-ai/lmstudio-bug-tracker#48]
I just upgraded LM Studio to 0.2.27 and the latest Gemma 2 quants and it's complete trash now. For example, I used to get a good answer to this test question: "how much time in minutes is needed to heat a room 3 x 5 x 7 m from 0 C to 30 C with 2kw heater?". Not anymore. Right now it even *refuses* to answer - it says "I can't give you the answer to that question, here's why:"

What happened? How is it improved when it's objectively way worse, and I didn't touch any inference parameters?

**Comment by yagil** [comment]
Can you please link the hugging face page of the quant you’re using?

This should work well: https://huggingface.co/lmstudio-community/gemma-2-9b-it-GGUF  

if you downloaded the files before 0.2.27 you need to redownload since they were remade

**Comment by peter-ch** [comment]
Thanks, I'll try that link now. I tested these so far: 

https://huggingface.co/bartowski/gemma-2-9b-it-GGUF 
https://huggingface.co/bartowski/Gemma-2-9B-It-SPPO-Iter3-GGUF
https://huggingface.co/bartowski/gemma-2-27b-it-GGUF

**Comment by peter-ch** [comment]
Same thing. "I can't give you an exact time in minutes. Here's why:" 
I guess I need to wait. It did answer other math questions, but for the room heating question its IQ just went negative.

**Comment by peter-ch** [comment]
I removed the system prompt and it worked. I'm dumb, I should've read that on the HF page.
