### ISSUE TITLE
Sending any text will return GGGGGGG

### ISSUE THREAD

**Issue by dbaiying** [lmstudio-ai/lmstudio-bug-tracker#49]
![image](https://github.com/lmstudio-ai/lmstudio-bug-tracker/assets/9245250/aa89c006-97fa-4063-b3d3-d5e19429323d)
<img width="1238" alt="issue" src="https://github.com/lmstudio-ai/lmstudio-bug-tracker/assets/9245250/3a877df8-aa48-4539-9bdc-134b7f1a7aa2">

**Comment by emimix** [comment]
Same issue: if you turn off the GPU, it works fine.

**Comment by YorkieDev** [comment]
The model is broken, not much can be done to fix it.

**Comment by dbaiying** [comment]
> @dbaiying Qwen 2 requires the use of the ChatML preset and Flash attention to be turned on. 

It works,Thank a lit
