### ISSUE TITLE
Search for all models returns empty

### ISSUE THREAD

**Issue by ineiti** [lmstudio-ai/lmstudio-bug-tracker#61]
Problem: every search for a model turns out empty

Platform: MacOS with M2 Max

Things I tried:
- remove LM Studio and re-install
- `rm -rf .cache/lm-studio`
- download a proposed model from LM Studio, which DID work

Other potential important info:
- I used LM Studio in the beginning of '24, so perhaps there is some remaining configuration I didn't find...

**Comment by yagil** [comment]
Hi @ineiti this is due to Hugging Face stability issues at the moment. We are investigating with them

**Comment by ineiti** [comment]
@yagil oh, I see. Today it seems to work just fine, thanks.

Perhaps adding a "network timeout" error message would be helpful then.

**Comment by ernestp** [comment]
Still happens

**Comment by capodieci** [comment]
Happening to me since a few days ago, and still happening today...

**Comment by pmarreck** [comment]
I haven't been able to search models for days.
I'm on the beta track.

**Comment by yagil** [comment]
@capodieci  @pmarreck this might fix it for you: https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/294#issuecomment-2581576638
