### ISSUE TITLE
Feature Request: Purge all chats button

### ISSUE THREAD

**Issue by pachacamac** [lmstudio-ai/lmstudio-bug-tracker#70]
Hope this is an okay place for feature requests.

I know you can just delete files in `~/.cache/lm-studio/chats` but thought it would be nicer if users can do it via the UI.

**Comment by pachacamac** [comment]
I'll close this since there's now a "reveal in finder" button which pretty much serves the use case. Thanks

**Comment by ghost** [comment]
Respectfully this still needs work @pachacamac . Decent apps need a way in the interface to do this not reveal in finder and try to figure it out. Please add a purge all chats button thats easy to find near the chat window. Thanks

**Comment by pachacamac** [comment]
Hey @codeguy2015 I'm not one of the maintainers, I just opened this issue from my own user perspective. For me personally the reveal in finder functionality is 'good enough'. I suggest if you still like to have the purge button, reopen the issue and re-raise your argument.
