### ISSUE TITLE
Failing to Load Llama 3.1-Instruct

### ISSUE THREAD

**Issue by jetlime** [lmstudio-ai/lmstudio-bug-tracker#77]
While loading the model "lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q8_0.gguf".

I obtain the following error:

```
llama.cpp error: 'done_getting_tensors: wrong number of tensors; expected 292, got 291
```

**Comment by yagil** [comment]
Hi @jetlime please try LM Studio 0.2.31. You can download it from https://lmstudio.ai

**Comment by jetlime** [comment]
It works, thanks. Sorry about that, I wasn't aware about the newer version :)
